apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    POSTGRES_DB: {{ .Values.secrets.encryptedData.POSTGRES_DB }}
    POSTGRES_PASSWORD: {{ .Values.secrets.encryptedData.POSTGRES_PASSWORD }}
    POSTGRES_USER: {{ .Values.secrets.encryptedData.POSTGRES_USER }}
  template:
    metadata:
      name: {{ .Values.secrets.name }}
      namespace: {{ .Values.namespace }}
    type: Opaque
