apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulSet.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulSet.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulSet.name }}
    spec:
      containers:
        - name: {{ .Values.statefulSet.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.statefulSet.containerPort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: POSTGRES_DB
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volume.name }}
      spec:
        accessModes: [ "{{ .Values.volume.accessMode }}" ]
        resources:
          requests:
            storage: {{ .Values.volume.storage }}
