apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.active.name }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.active.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.active.name }}
            port:
              number: {{ .Values.service.active.port }}
