apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: {{ .Values.sealedSecret.encryptedData.SPRING_DATASOURCE_PASSWORD }}
    SPRING_DATASOURCE_USERNAME: {{ .Values.sealedSecret.encryptedData.SPRING_DATASOURCE_USERNAME }}
  template:
    metadata:
      name: {{ .Values.sealedSecret.template.name }}
      namespace: {{ .Values.namespace }}
    type: Opaque
