apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.active.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.rollout.name }}
  ports:
    - port: {{ .Values.service.active.port }}
      targetPort: {{ .Values.rollout.containerPort }}
  type: ClusterIP
