namespace: petclinic-prod
rollout:
  revisionHistoryLimit: 3
configMap:
  data:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.petclinic-infra-prod.svc.cluster.local:5432/petclinic"
image:
  tag: prod-2172628c2ca824744775497d1d3d60f465b830db
ingress:
  active:
    host: petclinic.k8s-5.sa
  preview:
    host: preview.petclinic.k8s-5.sa
sealedSecret:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBBoPISOXNDuiZHHTQnVeyGDxgd+QPmUH4Q5fBImlHfCe/LTIaoSp6Y7ZIyqYJytz2HieJrzmdFAn24cZtz4cC5hKmcg6bqORVQAowaxjc8Dv7NOPpM4+yarPkoj2z7l7Sataqb/I2tvp3Q4oNjEme9sSm06eJbJRSPyrsR62byCkhtSIHPfHSkgALGnVVw6+kd6NTw4MSg9p0Ug2K2fMY0yuyr67trrWgElGgYsb9hlQBZWzYSYc6/DYs+BHwo2AqnZeD7yBaIKg5zzncHbr0XDuF042Sf2EObWUIUlV8W5uORfhIqOR/c9pGHI15z5J39RuABJgjVHzZR0Fcj1vzbVUtNtTzQqLAPz69pOn90Jo9mHySVuB8IsNviTHHboKN8mD5UYngTM4uZO4p69qMqnHkzr+Qftpg7sozkOgH+S/expbqLAtC2YALw9PAsJb+VpoT74dCiKdMBVsz8XfK/46Nqjg7qGCTczFbFSd97s7N0oKKBhs+iHy/A8ucKxJEbEVzGv3VSyvwos1ynR2FKXYLPsxNc5K44Y4zFJGmHFjHsMiEemTL8m+IvuDw8vEkYvDqmCi8bDF7JEsEx5Tk/cP67tXyJjXx12CQ6PEYom7oIU/s7dFcf67IDIjfDcAy0pl/xKjDuYd2T63k1zoBsGtR1GzuCXGGDzXZRD1rTJ8l0WWUrolrJXBg0ecmCYdg4vnotFkQdw24=
    SPRING_DATASOURCE_USERNAME: AgAZ/km7JL1FkRTIyluaYk/DVDGqk61vmh4MjmeiH1dV+KttodsCgyCnIlY7LU4IXk82ZMz3cpjcWe+OCKiow23el2t8agVRglLAJl8zdAfD4seCxNyYfzr7atEnY+DVaYij6f4IYhhh+lsepxMt1bvpZRJ+vqnDD3cEQU49X5Zul+NfGqIJf30YJuHONmSoYXDfIoTn7oFQ5ccvDzhvbZMiBzB2kG1QPPdBAdIbvUW/e3puartNHLZAWpkiJ5ht2mresCygEv/MtzMllMOqwqv8TewchfTa658NX6Wo6jOdQNnrs2jTVKRwg2bSzzPGWmxorWW+E2g5mvabeEoALW/1pWsFSBrrmO2SMqsdQCnYdR6KPvdNZsxdNXEnulZmMVxX58K7ZFkoBsFpIkYxL3AiGwUU1kS4aVZRJmHwNZw+c0lEa+G+ugY7YYRcpQBpHrkQPLriyKXgbxUAv8W6J69sJekF8VjqUJONmERhaPWDNKyb1wisw1PfCvtjRNzNCIvhBtA3pP0fuNC3ipdDn96qiFdiQ5RXtMnp8MnpOF4QQRW3bpKJ6cLdYxJt/RwdOgb8jZ7cLiTKvr7dfzrW3yi9eZZDSGruW4osNq0iJIRd4oxHviiOSr+9UUoXFweT235D+awsq6ZHgW+NBrQtRM0+glMxbATLREGuTep68AO1qgvCUF9UajEnvI2XNmQZori64B3FtsEg6A==
