statefulSet:
  name: postgres
  replicas: 1
  containerPort: 5432
service:
  name: postgres
  port: 5432
image:
  repository: postgres
  tag: 18.1
volume:
  name: postgres-data
  mountPath: /var/lib/postgresql
  accessMode: ReadWriteOnce
  storage: 5Gi