apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.petclinic-infra.svc.cluster.local:5432/petclinic"
