---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic-ingress-preview
  namespace: petclinic
spec:
  ingressClassName: nginx
  rules:
  - host: preview.petclinic.k8s-5.sa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: petclinic-preview
            port:
              number: 80
