---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: petclinic-db
  namespace: petclinic
spec:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgA3Ek5NSqAt2EcljnvMcXUROEbZpK9pa7vQshv/LwyJmo0EBwMJH8wW86rIArDuxKT3NqlvNc7v6saiOKegB+w0rFXgLFBUcsNxTUDyBpl6KfitsyJ+8MqcY41lsvdjIpth4k/J0F60kv6sjvJy3QrNb1+R6hBT3mRagsjvR+Py7mIdR8aK4VBaPWW0PmObaFYH9vx4hRn0QNrqVFAERkB1qLSF4/lRhM4BD1s7aVzR1AqQLiV9umb8gohocS94m1YONPwyh/PNnWbfBNTHCXzaGMCO2Q2p/Vv9RZPaiim28kn9wsPzHNBE34uSzvSElc0k3H6csxsmWQiya1nUwZ7g8Vqxwz3goz5jum27VfoqNlSykRqoRlk8LlRjD+4gUxr8+WCCXfTOuhNPDcGgMt6jB4pWtzDEHKSxDgMTz9rjzs0gQa8kAICPgq17w1SuFTrByyytuIVreaZzJXO+5HdW4AOTYIGjNYk0q+1cuXQfuAHiKbeigIQ225f+o+UFiXt3EsLKYoON/evskxUsqW1rrvBbuRvvef+RkSNwAnshOH+SooLfQHA043ETpC6kmhPl47ZPMo3J2efZR6iPk1ktr9E3U0tWzZ1CBKnLmk8TRaWHaQmFLYD7aDEB126fO4YM18yKCP04vksoiSBONNUy+yL3Nef3QrJPum0IKvNmqDDaBQaKSUz+wwjBwOzk68s9XxJ/884QCd0=
    SPRING_DATASOURCE_USERNAME: AgCeGCONyHkh7N2wcAYHR9GuZ+9QCG9mhi88dt9zD1YwXjbo9XXBKslOM2r0kW8R330aeSWqIi1sCa6RTb+XLMJIHTRgx/3PuhEa2+ftv4zpUl5T6BHI/0igdjFnkgX27AlJUGp63K/ySNGzsIk9a6ylMQo5R92giHnw934vJdQWVXMgvcHka93IdiBwrMqNJfY449ibTv1Yz6RxeNLV+sxIpTMUNT+0yVXJE9zbITpKUjn65MR594OFZz01V9AaFrfukCO4FGWHMFUEBxCy3B+tG25wxSN9x1iWorer5Ki/X+/831rzIuMCFwJ/iftczG5DK+S+xRZgntaaPffYtHkbomLRWJyY94zyK7G+Cj/V0iOzRYBsvpOHqf8c2pD/goEIBzkA0oavVmKyTKZYOlMVr3cK2GOAOPN2ddfzgiYm7qQJhQy1F52Oq6uWY62WTH/3ehqK1poc1dhN1+gc9/SnBa62b/9Z+UZNG2MzjwVq4N23UP3CGFTgmIMZNM3AffC+RaA0MQV6vzN1WmxTNBcRXmxX5Kja0obQLhljM0lkcuwHHVrMuSzlcmi4l3mh1AxTJR75qOKeJJyfqjs+XobcC/nT6uWyktASukCPJqdFgR2yNyEDBXzN0eNGeNbJvOgmfiBh6A4IyuXd/DRtQYvffIB7ziWwabGqFzUEt+Z84IpNOphS7GqYorDhDnsvDHgDvsLUvTkJywk=
  template:
    metadata:
      name: petclinic-db
      namespace: petclinic
    type: Opaque
