namespace: petclinic-dev
rollout:
  revisionHistoryLimit: 2
configMap:
  data:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.petclinic-infra-dev.svc.cluster.local:5432/petclinic"
image:
  tag: dev-latest
ingress:
  active:
    host: dev.petclinic.k8s-5.sa
  preview:
    host: dev-preview.petclinic.k8s-5.sa
sealedSecret:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgBagtR2fH7+DyWv4cfZCr+p+EGEjePjvLZR21ErxHEGLjFcC0/KjoW5Gp8RTBnjHJypIku9VSjyaW2hSuVbe5f9LAlKNo9egJfzX8CdP/4BeWOhSLusIyIh3bqVBSAlfuwEXkyIvM2Mq3LrBEDsJ8WZ2257TDZvEHGX7gCBMVv+X6lRvt/FwtdkscP36h0K4koz/RbBSYhC1VMySaiaJNzSpmAdLPFJFIOGYBG+XhpoK36HiXG+FTQwXbOhJae+DV3BalHyMiWjLYizxB9G7NQES1oAl1dIf8yn2Ov2NuGtaUUZM3D7i8bVsoS5jNvLtB4hNBNpLoHmx9NBb2gs41QltpMH3ylZmalzW+EdFPuDrn5ez1na1mPSkdhoXZuNaF55WILvRfTqWH3wuXWzksrkFuVm7xq3JwxosLn2eg0ypGK2E69L8zzyckBpgBC/VR0JX1i+B7k8t5BE6SyH/t7KCdgZgkShQJXYPAQqpZqIlzjSxMkMfS/NOlI1x+4KJf4dYupP/1XlcwZtvD2VNtChBsyP5rT8AwUxO5pf68KtIJLFbKN/fcXzlEE/bkPrLurL+LyINas5/1OZQi8pcwwxG90SwJS6Y6k0ZPV63BNKhJt1gcb5GXPLkLe+QYeQLF6SX4LgP/aLAjxOdhCCChCOYfjNMU/boNVI4DhmcrNcyhlsmojJTQ0pbju3c4Z95HyCwW/x77N3Wvc=
    SPRING_DATASOURCE_USERNAME: AgBfeRxnSOVEY2CqCld2PYjOJ5xsDQQj1z7esCQik4URycV3x4OwhYPNv5Xn1N145LxSIY8fLGoeyv97vSQrQ7Y7GPj2TqDKW1+n2RpXMI3EeRlqG9z3DoZXb19BnzY+y3fMXD57w96PUhIQUSa9ZRkrZoBj8w9tT4bs3dCOiAHPLmOUMxXrrgaIpjyjc1k63chEHEbQRRtAuc63fAZhBJhKph9reGmMUggNFFC8fXLREgzI+GTVkDdmTxM5N6XyvnAP9zGHaWqV+EByo51TRS2MDyp957lGxf1XclootkPAdMkPYTu1FR96YWPvRJrHY2u2zGaT2d4vNUeHFDD0VaqUc6rjYlFjHxzkEiEwyX+xq5xcAxlsR4M/kvq+GABIbOx3Rr5Kkpg3G8CNN59hDFF8JTz+Nak4WgPL1wgGcbcUjrGff1oD2pb0b5OHdU1g4W0SbfkclY3TlJfssc8tlezosE601Cxp1tR/3VMCD5n2LdgCfe+MbG57acmQelHDtWDnRvMlHB58OctYDXIW9+F8hPyU8QpJ5QcKExKWOFtchKUCrTDR+qiTESVtDwYDMDuAF21oxulUUGs47HwIyjtv2CeRjZhaf/C/baxsWCskpT/6M+88olYzjkOAk3P7TBLfHRBhaBpIUdwrnx04P1zSciY+VTa4PY/OcZgJ68YtiRNYUYNfPTMx0let5Zx/1/tYP9xyuUCv8g==