namespace: petclinic-dev
rollout:
  revisionHistoryLimit: 2
configMap:
  data:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.petclinic-infra-dev.svc.cluster.local:5432/petclinic"
image:
  tag: dev-6a8cac97fc930afea4e9788250196ee4e581d64e
ingress:
  active:
    host: dev.petclinic.k8s-5.sa
  preview:
    host: dev-preview.petclinic.k8s-5.sa
sealedSecret:
  encryptedData:
    SPRING_DATASOURCE_PASSWORD: AgAAxPnKC3nFXwYF5H8FZcrNNstzIsRaGevprZENh8APWAfepIMHZ9pGHDfOaWTuwrcJ95xJOhhXEhxMfQpG3ZCVWCp7yx5UHzwDUjmg4txQsrQZAsu7wL17VWF3yV8bacxjDlPKLGjPyn00xgXsAGuG94NpoPcgDmbKnRpLA3wPHZAG1ejKvs+eT6DHM1x3FzuPnWCSXOxjRXbpWsJBXv3B670eFqUii7/YzKmpeSDI9aIQUZZd2KJREANsCEd6HK+CzMjOr38Y8WF49OuJLuQoPy6uenL3Z68HT79LpuxkYYpJqxKVrKVlzSBs9qswTHNwcLvVosvFx3WG+tmUD1/JbLOBvoKzXtsgtUZYAnjOoZBQBIG3q7yg3xCT9biAo5h9hQuF4ekORm3WQuMqelVfNqbVIp+dU23juPzpCrHmFAZ40wgzgwXSfzOoiwg8Lj09edUim3rOYiFPoon0T0Y9mVxMsCQ1pPnmcBEzuEzqT6yGBuACG3gFte0KGj38M62399sDwdo/2yPrcMZVeGVLTMmEF/U4k6KS+6H997bbZfLWczHNDHQeJU8+fMHaJ3n7hEZgTii+9f0xjP5Yo/ZPxp7hNhb3iLPvA1ajxafw+bRLYuG5ZuxCKUGVUbi8N7DSuiljI00gaaQKAEI0wj970fh4eeP31IsT4PY7dXA5b8HWaluJy5G4yuJ+zDolO7Nk0dbVeGQMkes=
    SPRING_DATASOURCE_USERNAME: AgBNHiHVT3UeEgSBILa4S0gKwbIQxGIAXn9UiAPSOTw6ReRp1n1/CtqRqjHUX/Qy+ca4EYHjlsOGwMGvICm4Mve/z5D6XFiClOVAk1G6blhnAKELJYlkLYUqC1cS3NDHIvy5GG28AeXh8NHDnPYjEMXUR84Rjlue2qqXfSBfG9M1uPNT75KZlJL4ij1VnuyAQDWrOkAlGX+NaI7+i1jIrfm4FGblDxn48w0j7LBPvlpshGqepk+kP17xbHvbCM664I7sXtOomC6xJJaI5Q4c1LUH+4gPFPQsgeZ1qrTWsdB32kL9nIGs7ECBCTpEV2jjP6Hv4W0M927hT5Tdw+IHUC+eHZzhxZja0njSRRqgSHExpDN40cW81wI2XUgNMtJjoHfVk5NgdA2DAQuAAJ4Taba2TLr/mD1POkTtsVtZs6JRIS/Ktus031rB0WiAOImT3mXx6XT9XCFXL2kHx34n7kTltJlOGqo+7hlr+W3s8Las53D2COomWKna4tuWwUuqInO8jSmkUmRQ8hf4IENU3zo1pzx0wZegZaa/oO7lk8QWX+N7Kz06t1Aqr31pzrUVTd+VjnF3pdMwz/Nie67CtevMjc7mZ82lDD1hEV1NBvsKaEGciQJqAsiUmwaNU87zMmE0RMBD5/NfFB/QX1iV0uF4QkJTkbhTiAtF+HtP0DEqkdfJ8seFJGShomGR52zlUxOSLojJZwubjg==
